import React from 'react';

export default function TermsOfService() {
  return (
    <main style={{ maxWidth: 700, margin: '40px auto', padding: 24, background: '#fff', borderRadius: 12, boxShadow: '0 4px 24px #0001', fontFamily: 'Inter, sans-serif', color: '#222' }}>
      <h1 style={{ fontSize: 32, fontWeight: 700, marginBottom: 24 }}>Terms of Service</h1>
      <p><strong>Last updated:</strong> June 17, 2025</p>
      <p>By accessing or using ApexSalesAI (“Service”), you agree to these Terms of Service (“Terms”). If you do not agree, do not use the Service.</p>
      <h2>1. Use of Service</h2>
      <p>You may use the Service only for lawful purposes and in accordance with these Terms.</p>
      <h2>2. User Accounts</h2>
      <p>You are responsible for maintaining the confidentiality of your account and password and for all activities under your account.</p>
      <h2>3. AI Content</h2>
      <p>ApexSalesAI provides AI-generated responses. We do not guarantee the accuracy, completeness, or suitability of any content generated by our AI.</p>
      <h2>4. Privacy</h2>
      <p>Your use of the Service is also governed by our Privacy Policy.</p>
      <h2>5. Prohibited Conduct</h2>
      <p>You agree not to misuse the Service, including attempting unauthorized access or using the Service for illegal purposes.</p>
      <h2>6. Termination</h2>
      <p>We may suspend or terminate your access to the Service at our discretion for violations of these Terms.</p>
      <h2>7. Disclaimer & Limitation of Liability</h2>
      <p>The Service is provided “as is.” We disclaim all warranties and are not liable for any damages arising from your use of the Service.</p>
      <h2>8. Changes to Terms</h2>
      <p>We may update these Terms. Continued use of the Service constitutes acceptance of the new Terms.</p>
      <h2>Contact</h2>
      <p>For questions, contact us at <a href="mailto:support@apexsalesai.com">support@apexsalesai.com</a>.</p>
    </main>
  );
}
